services:
  postgres:
    image: postgres:15
    container_name: mandril_backend
    restart: unless-stopped
    environment:
      POSTGRES_USER: mandril_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mandril_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: 