export const errorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',

  SESSION_EXPIRED: 'SESSION_EXPIRED',
  LAST_VARIANT_CONFLICT: 'LAST_VARIANT_CONFLICT',
  CATEGORY_HAS_ACTIVE_PRODUCT: 'CATEGORY_HAS_ACTIVE_PRODUCT',
  CATALOG_HAS_ACTIVE_PRODUCT: 'CATALOG_HAS_ACTIVE_PRODUCT',
} as const;
