export const errorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  BAD_REQUEST: 'BAD_REQUEST',

  SESSION_EXPIRED: 'SESSION_EXPIRED',
  LAST_VARIANT_CONFLICT: 'LAST_VARIANT_CONFLICT',
  PRODUCT_WILL_BECOME_WITHOUT_ATTRIBUTES: 'PRODUCT_WILL_BECOME_WITHOUT_ATTRIBUTES',
  CATEGORY_HAS_ACTIVE_PRODUCT: 'CATEGORY_HAS_ACTIVE_PRODUCT',
  CATALOG_HAS_ACTIVE_PRODUCT: 'CATALOG_HAS_ACTIVE_PRODUCT',
  SALES_CHANNEL_HAS_ACTIVE_ORDERS: 'SALES_CHANNEL_HAS_ACTIVE_ORDERS',
} as const;
