export const SUPPLIER_ORDER_STATUS = [
  'PREPARING',
  'IN_TRANSIT',
  'PARTIALLY_RECEIVED',
  'RECEIVED',
  'CANCELLED',
] as const;
export const SUPPLIER_ORDER_TYPE = ['PURCHASE', 'COMPENSATION'] as const;
export const SUPPLIER_ORDER_REVIEW_STATUS = ['PENDING', 'IN_PROGRESS', 'COMPLETED'] as const;
export const SUPPLIER_ORDER_RECORD_ORIGIN = ['SYSTEM', 'LEGACY_IMPORT'] as const;
export const SUPPLIER_ORDER_CURRENCY = ['PEN', 'USD'] as const;
export const SUPPLIER_ORDER_EXPENSE_TYPE = [
  'INTERNATIONAL_SHIPPING',
  'CUSTOMS_TAXES',
  'LOCAL_FREIGHT',
  'OTHER',
] as const;
export const SUPPLIER_ORDER_RECEIPT_REVIEW_STATUS = ['PENDING', 'COMPLETED'] as const;
export const SUPPLIER_ORDER_ISSUE_TYPE = ['SHORTAGE', 'DEFECTIVE', 'WRONG_PRODUCT'] as const;
export const SUPPLIER_ORDER_ISSUE_STATUS = ['OPEN', 'CLOSED'] as const;
